baseURL = 'https://reviews.cat/'
languageCode = 'pt'
paginate = 5
title = 'Reviews.cat'
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpire = false
defaultContentLanguage = 'BR'

[services.googleAnalytics]
ID = 'G-XHFF1V9ZWT'

[minify]
disableXML = true
minifyOutput = true

[outputs]
home = ["HTML", "RSS", "JSON"]

[params.homeInfoParams]
Title = 'Reviews.cat'
Content = """
Vamos juntos descobrir produtos incríveis! 🌟
"""

[params.assets]
disableHLJS = true
favicon16x16 = "icon.png"

[params]
env = 'production'
author = 'Vitor Hugo'
ShowShareButtons = true
ShowReadingTime = true
displayFullLangName = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
ShowAllPagesInArchive = true
ShowPageNums = true
ShowToc = true
DateFormat = ":date_short"

[languages.BR]
languageName = "Português"
weight = 1

[[languages.BR.menu.main]]
name = "Buscar"
url = "search/"
weight = 10
